### ISSUE TITLE
Orne-γの回路 - 緊急停止ボタン

### ISSUE THREAD

**Issue by shulace13** [open-rdc/multi_view_image#18]
現在緊急停止ボタンがスイッチとメイン基板の間にあるので押すと全部落ちるようになっております。
これをモータードライバと電源の間に設置して、緊急停止ボタンを押しても全部落ちずにモーターに指令が送られないだけになるようにしたいです。

**Comment by yasuohayashibara** [comment]
他のorneはそのようになっていますので，回路を追加してください．

**Comment by shulace13** [comment]
わかりました、します

**Comment by shulace13** [comment]
来週の水曜日にりゅうせい君と行う予定です。

**Comment by shulace13** [comment]
緊急停止ボタンの導入は完了しました。
