### ISSUE TITLE
THETAの遠隔操作

### ISSUE THREAD

**Issue by shulace13** [open-rdc/multi_view_image#19]
佐藤くんが結構進めてくれているので報告できるように立てました。まだROS経由ではありません(?)

**Comment by NaokiSato102** [comment]
まだROS経由ではありません。

**Comment by NaokiSato102** [comment]
THETAの制御に使用しているgPhoto2はPythonとの連携？Pythonにおいて使用？するためのライブラリがある。これを用いるとより細かく、ThetaAPI(USB:MTP)に忠実に、制御ができると思われるため、導入しようとしたが、エラーが発生した。
PythonにおけるgPhoto2に発生したエラーを探るために公式Readmeを読むと、「python-gphoto2のREA​​DMEには、「dev」パッケージをインストールする必要があることが明確に記載されています。：https://github.com/jim-easterbrook/python-gphoto2#dependencies　（訳）」との記述を発見したが、そのパッケージをどのようなコマンドでインストールすればよいのか、正確なパッケージ名はいかなるものかが推測できなかった。

　そのため、改めてしっかりとエラーを読んだところ、「ERROR: command “pkg-config --modversion libgphoto2” failed」との記述を見つける。これを頼りに検索したところ、
このページに正しい前提ソフトのインストール方法が記載されていた。https://stackoverflow.com/questions/56755706/error-command-pkg-config-modversion-libgphoto2-failed/56777187
「sudo apt install libgphoto2-dev」を実行

　その後「sudo pip install  gphoto2」を実行したところ正常にインストールできた。

　そして手持ちのMTPデバイス、Nexus6P(スマホ)でサンプルコードの試験をしたところ期待通りの動作となった。

月曜以降、Python-gPhoto2(以後Py-gPhotoと称する)の試験に移る。

**Comment by NaokiSato102** [comment]
しばらくこっちで進捗上げてませんでした。

開発中のコードをpush？したいのですが、ここではどのようにやればいいんでしょうか？

**Comment by NaokiSato102** [comment]
これまだ立てておく必要ありますか？1週間返信なしの場合異議なしとみて閉じます。
