### ISSUE TITLE
Readmeとライセンスの記載

### ISSUE THREAD

**Issue by NaokiSato102** [open-rdc/multi_view_image#20]
Readmeとライセンスの記載を行うべきではないかと思ったのですが、どうでしょうか？

**Comment by NaokiSato102** [comment]
ライセンスは、ptpcam、gPhoto2とともにGPLなのでこれに準拠し同様にGPLにしようと思います。
バージョンは使用通信ライブラリのライセンス状況を鑑みて3が妥当と思っています。

参考情報
gPhoto2：GPL：Version 2, June 1991
libgPhoto2：LGPL：Version 2.1, February 1999
python-gPhoto2：GPL：Version 3, 29 June 2007
libptp2 ：GPL：Version 3, 29 June 2007
ptpcam：GPL：Version 3, 29 June 2007？(未確認：記載箇所が見当たらない。しかし、libptp2と同じと思われる。)

**Comment by shulace13** [comment]
時間があれば，それでお願いいたします．

**Comment by shulace13** [comment]
ライセンスを付与していただいたので閉じます
