### ISSUE TITLE
位置と姿勢に紐づけされた動画から任意の位置の画像を提示するシステムの構築

### ISSUE THREAD

**Issue by yasuohayashibara** [open-rdc/multi_view_image#8]
位置と姿勢に紐づけされた動画から任意の位置の画像を提示するシステムを構築する．

材料として，
・地図データ（画像ファイル）×１
・Thetaの画像データ（0.5mおよび1.0mの高さの画像のデータ）　×２
・位置・姿勢データ（0.1秒ごとの自己位置推定の値，csv）※　×２

※それぞれの画像データに対して個別の位置・姿勢データを用意する．

**Comment by NaokiSato102** [comment]
これまだ立てておく必要ありますか？1週間返信なしの場合異議なしとみて閉じます。

**Comment by yasuohayashibara** [comment]
開発リソースがありませんので，閉じます．
